public enum EnemyCode
{
    GREEN_SLIME = 0, RED_SLIME = 1, PINK_SLIME = 2, BLUE_SLIME = 3, WENDIGO = 4,
    GREEN_HORN_SLIME = 5, RED_HORN_SLIME = 6, BLUE_HORN_SLIME = 7,
    GREEN_MUSHROON = 8, RED_MUSHROOM = 9, PINK_MUSHROOM = 10,
    WHITE_PYGMY = 11, GREEN_PYGMY = 12, BROWN_PYGMY = 13, BLACK_PYGMY = 14,
}